use super::report::RtcoStatus;

pub struct RtcoRule {
    pub pattern: &'static str,
    pub rtco_cmd: &'static str,
    /// Whether this command may be rewritten as the final pipeline stage
    /// (e.g. `git log | grep foo` → `rtco git log | rtco grep foo`).
    /// Ported from upstream rtk (523c803).
    pub pipeline_final_safe: bool,
    pub rewrite_prefixes: &'static [&'static str],
    pub category: &'static str,
    pub savings_pct: f64,
    pub subcmd_savings: &'static [(&'static str, f64)],
    pub subcmd_status: &'static [(&'static str, RtcoStatus)],
}

impl RtcoRule {
    // `Default::default()` isn't a const fn on stable, so `RULES` (a const array)
    // can't call it via `..Default::default()` — hence this associated const as the
    // const-context workaround. Once `const_trait_impl` stabilizes, drop this and
    // derive/impl `const Default` instead, then switch call sites back to
    // `..RtcoRule::default()`.
    pub const DEFAULT: RtcoRule = RtcoRule {
        pattern: "",
        rtco_cmd: "",
        pipeline_final_safe: false,
        rewrite_prefixes: &[],
        category: "",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    };
}

impl Default for RtcoRule {
    fn default() -> Self {
        Self::DEFAULT
    }
}

pub const RULES: &[RtcoRule] = &[
    RtcoRule {
        pattern: r"^(?:git|yadm)\s+(?:-[Cc]\s+\S+\s+)*(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree)",
        rtco_cmd: "rtco git",
        rewrite_prefixes: &["git", "yadm"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[
            ("diff", 80.0),
            ("show", 80.0),
            ("add", 59.0),
            ("commit", 59.0),
        ],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^gh\s+(pr|issue|run|repo|api|release)",
        rtco_cmd: "rtco gh",
        rewrite_prefixes: &["gh"],
        category: "GitHub",
        savings_pct: 82.0,
        subcmd_savings: &[("pr", 87.0), ("run", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^glab\s+(mr|issue|ci|pipeline|api|release)",
        rtco_cmd: "rtco glab",
        rewrite_prefixes: &["glab"],
        category: "GitLab",
        savings_pct: 82.0,
        subcmd_savings: &[("mr", 87.0), ("ci", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^cargo\s+(build|test|clippy|check|fmt|install)",
        rtco_cmd: "rtco cargo",
        rewrite_prefixes: &["cargo"],
        category: "Cargo",
        savings_pct: 80.0,
        subcmd_savings: &[("test", 90.0), ("check", 80.0)],
        subcmd_status: &[("fmt", RtcoStatus::Passthrough)],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^pnpm\s+(exec|i|install|list|ls|outdated|run|run-script)",
        rtco_cmd: "rtco pnpm",
        rewrite_prefixes: &["pnpm"],
        category: "PackageManager",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^npm\s+(exec|run|run-script|rum|urn|x)(\s|$)",
        rtco_cmd: "rtco npm",
        rewrite_prefixes: &["npm"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^npx\s+",
        rtco_cmd: "rtco npx",
        rewrite_prefixes: &["npx"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^fnm\s+(list-remote|use|install|uninstall|list|ls|current|default)(\s|$)",
        rtco_cmd: "rtco fnm",
        rewrite_prefixes: &["fnm"],
        category: "NodeVersionManager",
        savings_pct: 25.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(cat|head|tail)\s+",
        rtco_cmd: "rtco read",
        rewrite_prefixes: &["cat", "head", "tail"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^rg\s+",
        rtco_cmd: "rtco rg",
        rewrite_prefixes: &["rg"],
        category: "Files",
        savings_pct: 50.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        pipeline_final_safe: true,
    },
    RtcoRule {
        pattern: r"^grep\s+",
        rtco_cmd: "rtco grep",
        rewrite_prefixes: &["grep"],
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        pipeline_final_safe: true,
    },
    RtcoRule {
        pattern: r"^ls(\s|$)",
        rtco_cmd: "rtco ls",
        rewrite_prefixes: &["ls"],
        category: "Files",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^find\s+",
        rtco_cmd: "rtco find",
        rewrite_prefixes: &["find"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?tsc(\s|$)",
        rtco_cmd: "rtco tsc",
        rewrite_prefixes: &[
            "npm exec tsc",
            "npm rum tsc",
            "npm run tsc",
            "npm run-script tsc",
            "npm tsc",
            "npm urn tsc",
            "npm x tsc",
            "npx tsc",
            "pnpm dlx tsc",
            "pnpm exec tsc",
            "pnpm run tsc",
            "pnpm run-script tsc",
            "pnpm tsc",
            "pnpx tsc",
            "tsc",
        ],
        category: "Build",
        savings_pct: 83.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?(biome|eslint|lint)(\s|$)",
        rtco_cmd: "rtco lint",
        rewrite_prefixes: &[
            "biome",
            "eslint",
            "lint",
            "npm biome",
            "npm eslint",
            "npm exec biome",
            "npm exec eslint",
            "npm lint",
            "npm rum biome",
            "npm rum eslint",
            "npm rum lint",
            "npm run biome",
            "npm run eslint",
            "npm run lint",
            "npm run-script biome",
            "npm run-script eslint",
            "npm run-script lint",
            "npm urn biome",
            "npm urn eslint",
            "npm urn lint",
            "npm x biome",
            "npm x eslint",
            "npx biome",
            "npx eslint",
            "npx lint",
            "pnpm biome",
            "pnpm dlx biome",
            "pnpm dlx eslint",
            "pnpm eslint",
            "pnpm exec biome",
            "pnpm exec eslint",
            "pnpm lint",
            "pnpm run biome",
            "pnpm run eslint",
            "pnpm run lint",
            "pnpm run-script biome",
            "pnpm run-script eslint",
            "pnpm run-script lint",
            "pnpx biome",
            "pnpx eslint",
            "pnpx lint",
        ],
        category: "Build",
        savings_pct: 84.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prettier",
        rtco_cmd: "rtco prettier",
        rewrite_prefixes: &[
            "npm exec prettier",
            "npm prettier",
            "npm rum prettier",
            "npm run prettier",
            "npm run-script prettier",
            "npm urn prettier",
            "npm x prettier",
            "npx prettier",
            "pnpm dlx prettier",
            "pnpm exec prettier",
            "pnpm prettier",
            "pnpm run prettier",
            "pnpm run-script prettier",
            "pnpx prettier",
            "prettier",
        ],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?next\s+build",
        rtco_cmd: "rtco next",
        rewrite_prefixes: &[
            "next build",
            "npm exec next build",
            "npm next build",
            "npm rum next build",
            "npm run next build",
            "npm run-script next build",
            "npm urn next build",
            "npm x next build",
            "npx next build",
            "pnpm dlx next build",
            "pnpm exec next build",
            "pnpm next build",
            "pnpm run next build",
            "pnpm run-script next build",
            "pnpx next build",
        ],
        category: "Build",
        savings_pct: 87.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?jest(\s+run)?(\s|$)",
        rtco_cmd: "rtco jest",
        rewrite_prefixes: &[
            "jest run",
            "jest",
            "npm exec jest run",
            "npm exec jest",
            "npm jest run",
            "npm jest",
            "npm rum jest run",
            "npm rum jest",
            "npm run jest run",
            "npm run jest",
            "npm run-script jest run",
            "npm run-script jest",
            "npm urn jest run",
            "npm urn jest",
            "npm x jest run",
            "npm x jest",
            "npx jest run",
            "npx jest",
            "pnpm dlx jest run",
            "pnpm dlx jest",
            "pnpm exec jest run",
            "pnpm exec jest",
            "pnpm jest run",
            "pnpm jest",
            "pnpm run jest run",
            "pnpm run jest",
            "pnpm run-script jest run",
            "pnpm run-script jest",
            "pnpx jest run",
            "pnpx jest",
        ],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?vitest(\s+run)?(\s|$)",
        rtco_cmd: "rtco vitest",
        rewrite_prefixes: &[
            "npm exec vitest run",
            "npm exec vitest",
            "npm rum vitest run",
            "npm rum vitest",
            "npm run vitest run",
            "npm run vitest",
            "npm run-script vitest run",
            "npm run-script vitest",
            "npm urn vitest run",
            "npm urn vitest",
            "npm vitest run",
            "npm vitest",
            "npm x vitest run",
            "npm x vitest",
            "npx vitest run",
            "npx vitest",
            "pnpm dlx vitest run",
            "pnpm dlx vitest",
            "pnpm exec vitest run",
            "pnpm exec vitest",
            "pnpm run vitest run",
            "pnpm run vitest",
            "pnpm run-script vitest run",
            "pnpm run-script vitest",
            "pnpm vitest run",
            "pnpm vitest",
            "pnpx vitest run",
            "pnpx vitest",
            "vitest run",
            "vitest",
        ],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?playwright",
        rtco_cmd: "rtco playwright",
        rewrite_prefixes: &[
            "npm exec playwright",
            "npm playwright",
            "npm rum playwright",
            "npm run playwright",
            "npm run-script playwright",
            "npm urn playwright",
            "npm x playwright",
            "npx playwright",
            "playwright",
            "pnpm dlx playwright",
            "pnpm exec playwright",
            "pnpm playwright",
            "pnpm run playwright",
            "pnpm run-script playwright",
            "pnpx playwright",
        ],
        category: "Tests",
        savings_pct: 94.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^((p?np(m|x)|p?npm\s+(exec|run|run-script)|npm\s+(rum|urn|x)|pnpm\s+dlx)\s+)?prisma",
        rtco_cmd: "rtco prisma",
        rewrite_prefixes: &[
            "npm exec prisma",
            "npm prisma",
            "npm rum prisma",
            "npm run prisma",
            "npm run-script prisma",
            "npm urn prisma",
            "npm x prisma",
            "npx prisma",
            "pnpm dlx prisma",
            "pnpm exec prisma",
            "pnpm prisma",
            "pnpm run prisma",
            "pnpm run-script prisma",
            "pnpx prisma",
            "prisma",
        ],
        category: "Build",
        savings_pct: 88.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^docker\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
        rtco_cmd: "rtco docker",
        rewrite_prefixes: &["docker"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^kubectl\s+(get|logs|describe|apply)",
        rtco_cmd: "rtco kubectl",
        rewrite_prefixes: &["kubectl"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^tree(\s|$)",
        rtco_cmd: "rtco tree",
        rewrite_prefixes: &["tree"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^diff\s+",
        rtco_cmd: "rtco diff",
        rewrite_prefixes: &["diff"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^curl\s+",
        rtco_cmd: "rtco curl",
        rewrite_prefixes: &["curl"],
        category: "Network",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^wget\s+",
        rtco_cmd: "rtco wget",
        rewrite_prefixes: &["wget"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(python3?\s+-m\s+)?mypy(\s|$)",
        rtco_cmd: "rtco mypy",
        rewrite_prefixes: &["python3 -m mypy", "python -m mypy", "mypy"],
        category: "Build",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^ruff\s+(check|format)",
        rtco_cmd: "rtco ruff",
        rewrite_prefixes: &["ruff"],
        category: "Python",
        savings_pct: 80.0,
        subcmd_savings: &[("check", 80.0), ("format", 75.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(python[0-9.]*\s+-m\s+)?pytest(\s|$)",
        rtco_cmd: "rtco pytest",
        rewrite_prefixes: &["python3 -m pytest", "python -m pytest", "pytest"],
        category: "Python",
        savings_pct: 90.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(pip3?|uv\s+pip)\s+(list|outdated|install|show)",
        rtco_cmd: "rtco pip",
        rewrite_prefixes: &["pip3", "pip", "uv pip"],
        category: "Python",
        savings_pct: 75.0,
        subcmd_savings: &[("list", 75.0), ("outdated", 80.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^go\s+(test|build|vet)",
        rtco_cmd: "rtco go",
        rewrite_prefixes: &["go"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[("test", 90.0), ("build", 80.0), ("vet", 75.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:golangci-lint|golangci)\s+(run)(?:\s|$)",
        rtco_cmd: "rtco golangci-lint run",
        rewrite_prefixes: &["golangci-lint run", "golangci run"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^bundle\s+(install|update)\b",
        rtco_cmd: "rtco bundle",
        rewrite_prefixes: &["bundle"],
        category: "Ruby",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:bundle\s+exec\s+)?(?:bin/)?(?:rake|rails)\s+test",
        rtco_cmd: "rtco rake",
        rewrite_prefixes: &[
            "bundle exec rails",
            "bundle exec rake",
            "bin/rails",
            "rails",
            "rake",
        ],
        category: "Ruby",
        savings_pct: 85.0,
        subcmd_savings: &[("test", 90.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:bundle\s+exec\s+)?rspec(?:\s|$)",
        rtco_cmd: "rtco rspec",
        rewrite_prefixes: &["bundle exec rspec", "bin/rspec", "rspec"],
        category: "Tests",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:bundle\s+exec\s+)?rubocop(?:\s|$)",
        rtco_cmd: "rtco rubocop",
        rewrite_prefixes: &["bundle exec rubocop", "rubocop"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^aws\s+",
        rtco_cmd: "rtco aws",
        rewrite_prefixes: &["aws"],
        category: "Infra",
        savings_pct: 80.0,
        subcmd_savings: &[
            ("sts", 80.0),
            ("s3", 60.0),
            ("ec2", 85.0),
            ("ecs", 90.0),
            ("rds", 80.0),
            ("cloudformation", 90.0),
            ("logs", 88.0),
            ("lambda", 90.0),
            ("iam", 85.0),
            ("dynamodb", 70.0),
            ("s3api", 75.0),
            ("eks", 87.0),
            ("sqs", 78.0),
            ("secretsmanager", 75.0),
        ],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^psql(\s|$)",
        rtco_cmd: "rtco psql",
        rewrite_prefixes: &["psql"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^sqlite3(\s|$)",
        rtco_cmd: "rtco sqlite",
        rewrite_prefixes: &["sqlite3"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^ansible-playbook\b",
        rtco_cmd: "rtco ansible-playbook",
        rewrite_prefixes: &["ansible-playbook"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^brew\s+(install|upgrade)\b",
        rtco_cmd: "rtco brew",
        rewrite_prefixes: &["brew"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^composer\s+(install|update|require)\b",
        rtco_cmd: "rtco composer",
        rewrite_prefixes: &["composer"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^php\s+artisan(?:\s|$)",
        rtco_cmd: "rtco php",
        rewrite_prefixes: &["php"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^php\s+-l(?:\s|$)",
        rtco_cmd: "rtco php",
        rewrite_prefixes: &["php"],
        category: "Build",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:php\s+)?(?:\./)?(?:(?:vendor/)?bin/)?phpunit(?:\s|$)",
        rtco_cmd: "rtco phpunit",
        rewrite_prefixes: &["bin/phpunit", "phpunit"],
        category: "Tests",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:php\s+)?(?:\./)?(?:(?:vendor/)?bin/)?phpstan\s+analy[sz]e\b",
        rtco_cmd: "rtco phpstan",
        rewrite_prefixes: &["bin/phpstan", "phpstan"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[("analyse", 65.0), ("analyze", 65.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:\./)?(?:vendor/bin/)?pest(?:\s|$)",
        rtco_cmd: "rtco pest",
        rewrite_prefixes: &["pest"],
        category: "Tests",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:\./)?(?:vendor/bin/)?paratest(?:\s|$)",
        rtco_cmd: "rtco paratest",
        rewrite_prefixes: &["paratest"],
        category: "Tests",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:\./)?(?:vendor/bin/)?ecs(?:\s|$)",
        rtco_cmd: "rtco ecs",
        rewrite_prefixes: &["ecs"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:\./)?(?:vendor/bin/)?pint(?:\s|$)",
        rtco_cmd: "rtco pint",
        rewrite_prefixes: &["pint"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^php(\s|$)",
        rtco_cmd: "rtco php",
        rewrite_prefixes: &["php"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^df(\s|$)",
        rtco_cmd: "rtco df",
        rewrite_prefixes: &["df"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^dotnet\s+build\b",
        rtco_cmd: "rtco dotnet",
        rewrite_prefixes: &["dotnet"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^du\b",
        rtco_cmd: "rtco du",
        rewrite_prefixes: &["du"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^fail2ban-client\b",
        rtco_cmd: "rtco fail2ban-client",
        rewrite_prefixes: &["fail2ban-client"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^gcloud\b",
        rtco_cmd: "rtco gcloud",
        rewrite_prefixes: &["gcloud"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^(?:\./gradlew|gradlew\.bat|gradlew|gradle)(?:\s+(test|build|clean|assemble\w*|install\w*|check|lint\w*|dependencies))?(\s|$)",
        rtco_cmd: "rtco gradlew",
        rewrite_prefixes: &["./gradlew", "gradlew.bat", "gradlew", "gradle"],
        category: "Build",
        savings_pct: 75.0,
        subcmd_savings: &[("test", 90.0), ("build", 80.0), ("check", 80.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^hadolint\b",
        rtco_cmd: "rtco hadolint",
        rewrite_prefixes: &["hadolint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^helm\b",
        rtco_cmd: "rtco helm",
        rewrite_prefixes: &["helm"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^iptables\b",
        rtco_cmd: "rtco iptables",
        rewrite_prefixes: &["iptables"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^make\b",
        rtco_cmd: "rtco make",
        rewrite_prefixes: &["make"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^markdownlint\b",
        rtco_cmd: "rtco markdownlint",
        rewrite_prefixes: &["markdownlint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^mix\s+(compile|format)(\s|$)",
        rtco_cmd: "rtco mix",
        rewrite_prefixes: &["mix"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^mvn\s+(compile|package|clean|install|test|verify|integration-test|failsafe:integration-test)\b",
        rtco_cmd: "rtco mvn",
        rewrite_prefixes: &["mvn"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^ping\b",
        rtco_cmd: "rtco ping",
        rewrite_prefixes: &["ping"],
        category: "Network",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^pio\s+run",
        rtco_cmd: "rtco pio",
        rewrite_prefixes: &["pio"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^poetry\s+(install|lock|update)\b",
        rtco_cmd: "rtco poetry",
        rewrite_prefixes: &["poetry"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^pre-commit\b",
        rtco_cmd: "rtco pre-commit",
        rewrite_prefixes: &["pre-commit"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^ps(\s|$)",
        rtco_cmd: "rtco ps",
        rewrite_prefixes: &["ps"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^quarto\s+render",
        rtco_cmd: "rtco quarto",
        rewrite_prefixes: &["quarto"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^rsync\b",
        rtco_cmd: "rtco rsync",
        rewrite_prefixes: &["rsync"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^shellcheck\b",
        rtco_cmd: "rtco shellcheck",
        rewrite_prefixes: &["shellcheck"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^shopify\s+theme\s+(push|pull)",
        rtco_cmd: "rtco shopify",
        rewrite_prefixes: &["shopify"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^sops\b",
        rtco_cmd: "rtco sops",
        rewrite_prefixes: &["sops"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^swift\s+(build|test)\b",
        rtco_cmd: "rtco swift",
        rewrite_prefixes: &["swift"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[("test", 90.0)],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^systemctl\s+status\b",
        rtco_cmd: "rtco systemctl",
        rewrite_prefixes: &["systemctl"],
        category: "System",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^terraform\s+plan",
        rtco_cmd: "rtco terraform",
        rewrite_prefixes: &["terraform"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^tofu\s+(fmt|init|plan|validate)(\s|$)",
        rtco_cmd: "rtco tofu",
        rewrite_prefixes: &["tofu"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^trunk\s+build",
        rtco_cmd: "rtco trunk",
        rewrite_prefixes: &["trunk"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^uv\s+run(?:\s|$)",
        rtco_cmd: "rtco uv",
        rewrite_prefixes: &["uv"],
        category: "Python",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^uv\s+(sync|pip\s+install)\b",
        rtco_cmd: "rtco uv",
        rewrite_prefixes: &["uv"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^yamllint\b",
        rtco_cmd: "rtco yamllint",
        rewrite_prefixes: &["yamllint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^wc(\s|$)",
        rtco_cmd: "rtco wc",
        rewrite_prefixes: &["wc"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^gt\s+",
        rtco_cmd: "rtco gt",
        rewrite_prefixes: &["gt"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^liquibase(?:\s|$)",
        rtco_cmd: "rtco liquibase",
        rewrite_prefixes: &["liquibase"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^ffs\s+",
        rtco_cmd: "rtco ffs",
        rewrite_prefixes: &["ffs"],
        category: "Files",
        savings_pct: 50.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
    RtcoRule {
        pattern: r"^hashline\s+",
        rtco_cmd: "rtco hashline",
        rewrite_prefixes: &["hashline"],
        category: "Files",
        savings_pct: 40.0,
        subcmd_savings: &[],
        subcmd_status: &[],
        ..RtcoRule::DEFAULT
    },
];
pub const IGNORED_PREFIXES: &[&str] = &[
    "cd ",
    "cd\t",
    "echo ",
    "printf ",
    "export ",
    "source ",
    "mkdir ",
    "rm ",
    "mv ",
    "cp ",
    "chmod ",
    "chown ",
    "touch ",
    "which ",
    "type ",
    "test ",
    "true",
    "false",
    "sleep ",
    "wait",
    "kill ",
    "set ",
    "unset ",
    "sort ",
    "uniq ",
    "tr ",
    "cut ",
    "awk ",
    "sed ",
    "python3 -c",
    "python -c",
    "node -e",
    "ruby -e",
    "rtco ",
    "pwd",
    "bash ",
    "sh ",
    "then\n",
    "then ",
    "else\n",
    "else ",
    "do\n",
    "do ",
    "for ",
    "while ",
    "if ",
    "case ",
];

pub const IGNORED_EXACT: &[&str] = &[
    "cd", "echo", "true", "false", "wait", "pwd", "bash", "sh", "fi", "done",
];
